# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a291fbd309b8f82f8861de05afb2f2023106b4bfe286c35ceb5ae5288260b4e1c95d72b3e83ad43c04856a5e1704119885d37257d8d29dc34dc6c1d1dbe57b

test:
  secret_key_base: e0018e53da0e3fff4d9ca2b66d002c89d8654dfc112d6dfc597c2bed1408cbb045a28098d50b70eca572a1dd889efcf5c0b1f37bb6e2710d1708c06163f01611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
